#!/usr/bin/env bash
# Script to display information about server domains

# Function to check domain and subdomains
check_domain() {
    DOMAIN="$1"
    SUBDOMAIN="$2"
    
    # Default subdomains to check
    SUBDOMAINS='www lb-01 web-01 web-02'

    # If no subdomain specified, check all default subdomains
    if [ -z "$SUBDOMAIN" ]; then
        for SUB in $SUBDOMAINS; do
            dig "$SUB.$DOMAIN" | awk '/ANSWER SECTION:/ { getline; print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
        done
    else
        dig "$SUBDOMAIN.$DOMAIN" | awk '/ANSWER SECTION:/ { getline; print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
    fi
}

# Call check_domain function with arguments passed to script
check_domain "$1" "$2"
