#!/usr/bin/env bash
# Script to transfer a file using SCP to a remote server

# Function to display usage information
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if number of arguments is less than 4, display usage
if [ $# -lt 4 ]; then
    display_usage
fi

# Assigning arguments to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Checking if the file exists
if [ ! -f "$PATH_TO_FILE" ]; then
    echo "Error: File $PATH_TO_FILE does not exist."
    display_usage
fi

# Using SCP to transfer the file to remote server's home directory
if scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/; then
    echo "File transfer successful!"
else
    echo "File transfer failed!"
fi
