#!/usr/bin/env bash
# Installs Nginx

# Update package lists to ensure we install the latest versions
apt-get update

# Install Nginx with the '-y' flag to automatically answer yes to prompts
apt-get install -y nginx

# Echo "Holberton School" into /var/www/html/index.html to create a basic index page
echo "Hello world!" > /var/www/html/index.html

# Start the Nginx service
service nginx start
