#!/usr/bin/env bash


# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Create index.html file with Hello World content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx (without systemctl)
service nginx start
