#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx, setting up a basic index page with "Hello World!"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up Nginx configuration.\n"

# Start Nginx service
sudo systemctl start nginx

# Allow Nginx HTTP traffic in firewall
sudo ufw allow 'Nginx HTTP'

# Give ownership of web files to the current user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!"
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx to apply changes
sudo systemctl restart nginx

echo -e "\nNginx configuration completed.\n"
