#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me with a 301 status

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up Nginx redirection.\n"

# Start Nginx service
sudo systemctl start nginx

# Allow Nginx HTTP traffic in firewall
sudo ufw allow 'Nginx HTTP'

# Give ownership of web files to the current user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Backup default Nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bckp

# Configure redirection in Nginx default site configuration
sudo sed -i '/^.*server_name _;/a \ \ \ \ location /redirect_me {\n \ \ \ \ \ \ \ \ return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n \ \ \ \ }' /etc/nginx/sites-available/default

# Test Nginx configuration for errors
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx

echo -e "\nNginx redirection configuration completed.\n"
