#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serves a page that would return a Hello World string
# Sets up a redirection and a custom 404 page

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a YouTube video
sudo sed -i '/server {/a\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
    }' /etc/nginx/sites-available/default

# Set up a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/server {/a\\
    error_page 404 /error_404.html;\\
    location = /error_404.html {\\
        internal;\\
    }' /etc/nginx/sites-available/default

# Restarting Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
