#!/usr/bin/env bash
# This script sets up Nginx and configures a custom 404 page and a 301 redirect for /redirect_me

echo -e "Updating package list and installing Nginx...\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nSetting up Nginx configuration...\n"

# Starting Nginx service
sudo systemctl start nginx

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Backup default site configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Set up custom 404 page content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Update Nginx configuration
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Custom 404 error page
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    # Redirection for /redirect_me
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply changes
sudo systemctl restart nginx

echo -e "\nNginx setup complete with custom 404 page and 301 redirection for /redirect_me\n"
