#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx,
# setting it to listen on port 80, serving a "Hello World"
# page, configuring a redirect, and setting up a custom 404 page.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service
sudo systemctl start nginx

# Allow Nginx HTTP traffic in firewall
sudo ufw allow 'Nginx HTTP'

# Give ownership of web files to the current user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!"
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure /redirect_me to redirect to a YouTube video
sudo sed -i 's/^\s*#.*rewrite.*;/\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

# Configure custom 404 page
sudo sed -i 's/^\s*#.*error_page.*;/\terror_page 404 \/error_404.html;/' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx

echo -e "\nCompleted.\n"
