#!/usr/bin/env bash
# This script installs and configures HAProxy to balance traffic between two web servers

# Install necessary software properties package
sudo apt-get install -y software-properties-common

# Add the HAProxy 1.8 repository
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update the package list
sudo apt-get update

# Install HAProxy version 1.8
sudo apt-get install -y haproxy=1.8.\*

# Define the load balancer configuration
load_balancer_config="\nfrontend http\n
\tbind *:80\n
\tmode http\n
\tdefault_backend web_back\n
\nbackend web_back\n
\tbalance roundrobin\n
\tserver web-01 100.25.202.17:80 check\n
\tserver web-02 34.207.62.126:80 check\n"

# Enable HAProxy to start on boot
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy

# Append the load balancer configuration to the HAProxy config file
echo -e "$load_balancer_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart the HAProxy service to apply changes
sudo service haproxy restart
