#!/usr/bin/env bash
# Backup and compress MySQL databases

# Check if a password argument is provided
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <mysql_root_password>"
  exit 1
fi

# Variables for the current date
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

# MySQL root password
MYSQL_ROOT_PASSWORD=$1
# Dump all databases into a file named backup.sql
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql  
