#!/usr/bin/env bash
#bash script that pings an ip address as an argument
# Check if argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Extract IP address from argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 "$ip_address"

