#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Remove the default symbolic link in sites-enabled if it exists
if [ -e /etc/nginx/sites-enabled/default ]; then
    rm /etc/nginx/sites-enabled/default
fi

# Create a symbolic link from sites-available to sites-enabled
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the nginx service to apply the changes
service nginx restart
