#!/usr/bin/env bash

# Display lines containing the word "bash" to get the PID of your Bash process
# Use ps command to list processes and grep for "bash"
#shellcheck disable=SC2009

ps -a -x -u -f | grep "bash"
