#!/usr/bin/env bash
#Script to display To infinity and beyond indefinitely
#print "i am invincible!!!" when receiving a SIGTERM signal

#Function to handle SIGTERM signal
terminate() {
	echo "I am invincible!!!"
	exit
}
#trap SIGTERM signal
trap terminate SIGTERM

#Infinite loop
while true; do
	echo "To infinity and beyond"
	sleep 2
done
