#!/usr/bin/env bash
#Script to display To infinity and beyond indefinitely
#print "i am invincible!!!" when receiving a SIGTERM signal

#Function to handle SIGTERM signal
#trap SIGTERM signal
trap 'echo "I am invincible!!!"' 15
#Infinite loop
while true; do
	echo "To infinity and beyond"
	sleep 2
done
