#!/usr/bin/env bash
#display best school 10 times with special case
#for the 9nth iteration

#initialize count
count=0

#using the if condition and the while loop
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
