#!/bin/bash
#configure firewall rules

# Enable UFW
sudo ufw enable

# set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH
sudo ufw allow 22/tcp

# Allow HTTP
sudo ufw allow 80/tcp

# Allow HTTPS
sudo ufw allow 443/tcp

# check UFW status
sudo ufw status
