#!/usr/bin/env bash
# Check if the script is running on Docker
if [ -f /.dockerenv ]; then
    # Configure /etc/hosts file
    sudo bash -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
    sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'
fi

